### ISSUE TITLE
Playtest Answers

### ISSUE THREAD

**Issue by amandaclement** [alexasalois/cart315-2021#3]
**How did the movement speed of the character feel?**
The movement speed of the character feels appropriate. Due to the size of the space you’re immersed in, I think that making the player move any faster than the current speed could be problematic since you would collide with the boundaries too easily.
 
**Are the controls easy to use?**
Yes, the controls are straight-forward and intuitive.
 
**What did the colours make you feel?**
The colours reminded me of a carnival or playground - flashy and playful.
 
**Does the player feel slow/constricted?**
The player speed feels appropriate but the space does feel a bit constricted. It feels like I’m trapped in a box and would like to have some more space to move around in.

**Comment by fredlabbe** [comment]
1. It felt smooth, and realistic. 
2. Yes they are, straight forward, conventional and easy to understand as someone who plays games 
3. Felt like a mysterious space movie from late 90s/early 2000s like Zathura. Felt nostalgic. 
4. Not slow, but constricted a bit because there isn't a lot of space to move from
