### ISSUE TITLE
PROTOTYPE 3: Playtest Questions

### ISSUE THREAD

**Issue by alexasalois** [alexasalois/cart315-2021#6]
Design Journal

This game is an endless runner where a mysterious little cube must avoid ghosts in the forest, otherwise the game ends. Where is he going? Where does this end? Who is he? 

This is an early stage so it’s mostly testing the main mechanism. I’ll be asking questions related to the game itself, but also the concept in general. :)

1. How does the speed feel to you? (the movement of the avatar, and the speed of the “endless running”)

2. Did you like the simple / minimalistic art style? Did you recognize that the background is supposed to be a forest?
 
3. If I decide to develop this idea further, each level would be a different colour background, which would be the various stages of a sun rising. In that case, the avatar is then running through the night and has to survive until the sun rises. **What meaning do you attribute to this?** 
 
4. When playing games like temple run, flappy bird, etc. (endless runners), how much do you care about the story? What do you notice the most about this format, that makes you keep playing?
 
5. If the game gets developed further and there’s more of a story to it, would you see yourself playing this on mobile or PC?  

P.S. I am not a very good programmer so this is the first time i actually got my unity project to work as a "game" ^^ so i know it's not super developed, but I am confident my final game will be actually fun and enjoyable :P

**Comment by sebchampoux** [comment]
Before answering the questions, I'll premise by saying that I wasn't sure if everything worked properly.  The background scrolled as I expected, but my character would always die within a few seconds of starting the game.  I saw that there was a ghost game object as well, but I never saw the ghost in my tests.  So I'll explain my experience below, hopefully I didn't miss something important.

> How does the speed feel to you? (the movement of the avatar, and the speed of the “endless running”)

It was a bit slow, I don't think it would pose much of a challenge to dodge enemies at that speed, unless the enemies moved really fast.

> Did you like the simple / minimalistic art style? Did you recognize that the background is supposed to be a forest?

Yes it looks nice!  I didn't immediately recognize that it was a forest but after reading the question I see the tree trunks and all.  Maybe some more vegetation or another layer to the background would convey the environment even better.

> If I decide to develop this idea further, each level would be a different colour background, which would be the various stages of a sun rising. In that case, the avatar is then running through the night and has to survive until the sun rises. What meaning do you attribute to this?

The two ideas I get from this scenario are either a heist, and the thieves must escape before the authorities catch them, or a prison break, that would happen at night then the escapees must vanish before being found.

> When playing games like temple run, flappy bird, etc. (endless runners), how much do you care about the story? What do you notice the most about this format, that makes you keep playing?

Not that much.  It's nice to have some context to what your character is doing but once the game starts the story of these games becomes irrelevant as it doesn't impact the gameplay.

> If the game gets developed further and there’s more of a story to it, would you see yourself playing this on mobile or PC?

In its current format, it looks like a mobile game concept to me, that I'd play to waste a few minutes of my time, rather than a game that I would sit down and really want to get immersed in a story or a long play session.

**Comment by CocoChao** [comment]
There was an issue while I downloaded your files folder. I am not sure if I was able to test all the features you included in your game. Hopefully, my feedback answers your questions.

**1.	How does the speed feel to you? (the movement of the avatar, and the speed of the “endless running”)**
The speed was okay, although I wished that it would slowly increase with time to add more difficulty to the game. I also noticed that sometime the ghost character would stay for the duration of the test, and other times it would disappear few seconds after the game starts.

**2.	Did you like the simple / minimalistic art style? Did you recognize that the background is supposed to be a forest?**
I like the minimalist background. However, I thought it was red curtains, like the ones in the theaters at first glance. I suggest that you add some branches or leaves to your trees to make them more recognizable. I presumed that the ghost was a sort of magician performing an invisible trick before reading your questions.

**3.	If I decide to develop this idea further, each level would be a different colour background, which would be the various stages of a sun rising. In that case, the avatar is then running through the night and has to survive until the sun rises. What meaning do you attribute to this?**
That would be an interesting concept to your game. The ghost character could also collect or avoid objects related to activities done at that moment of the day to pass the level (suggestion). I do not quite understand the question, but I guess that could mean the ghost is trying to survive throughout the day, so he can strive at night and scare the humans/animals away from the forest(?).

**4.	When playing games like temple run, flappy bird, etc. (endless runners), how much do you care about the story? What do you notice the most about this format, that makes you keep playing?**
When I play those games, I only focus on surviving and trying to beat my previous score. Seeing that score go higher every time gives me satisfaction and motivation to play again.
 
**5.	If the game gets developed further and there’s more of a story to it, would you see yourself playing this on mobile or PC?**
Yes. I would play this game to pass the time. A score counter would also be very useful, to see how much I can improve my score and/or survive longer in the game.

**Comment by PatrickChavez** [comment]
**1. How does the speed feel to you? (the movement of the avatar, and the speed of the “endless running”)**
The avatar movement was good, but the “endless running” speed was a little too slow. I feel that having the speed increase gradually over time could add some challenge to the game.

**2. Did you like the simple / minimalistic art style? Did you recognize that the background is supposed to be a forest?**
I like the cute, minimalistic style. I thought that the forest was a series of curtains.

**3. If I decide to develop this idea further, each level would be a different colour background, which would be the various stages of a sun rising. In that case, the avatar is then running through the night and has to survive until the sun rises. What meaning do you attribute to this?**
The cube got lost in a forest and once nighttime arrived, they were then chased by ghosts (perhaps these ghosts used to be people who died in the forest). Once the sun rises, the ghosts disappear and the cube can finally leave. Perhaps the forest is evil and traps unaware victims for a day?

**4. When playing games like temple run, flappy bird, etc. (endless runners), how much do you care about the story? What do you notice the most about this format, that makes you keep playing?**
The story is very minimal in these types of games, thus, the gameplay is their most important aspect. Usually, when playing these types of games, I always try to beat my high score; it’s a rewarding feeling to accomplish that feat. Endless runners are also easy to pick up and play, so they can get addictive. That being said, having some story is a concept I would like to see, as finding out what happens next in the narrative is a good motivator for me.  

**5. If the game gets developed further and there’s more of a story to it, would you see yourself playing this on mobile or PC?**
Both are fine for me; this could be the type of game that can be played in short bursts while going to work/school or be played in one sitting on a weekend.

**Comment by LeVieuxSinge** [comment]
### How does the speed feel to you? (the movement of the avatar, and the speed of the “endless running”)

It's very slow. Except for the moving background, you don't have the impression of movement.

### Did you like the simple / minimalistic art style? Did you recognize that the background is supposed to be a forest?

The art style is fine. However, I thought the background were curtains and not a forest.

### If I decide to develop this idea further, each level would be a different colour background, which would be the various stages of a sun rising. In that case, the avatar is then running through the night and has to survive until the sun rises. What meaning do you attribute to this?

I don't have any meanings but if your intention is to do an **infinite scroll** you shouldn't have an end point to your game. Also, adding multiple levels is contrary to the concept of infinite scroll. Where you thinking of adding difficulty / game modes through the progression ?

### When playing games like temple run, flappy bird, etc. (endless runners), how much do you care about the story? What do you notice the most about this format, that makes you keep playing?

I don't really care about the story when playing infinite scrollers like subway surfers. The endless continuity and increasing difficulty is what keeps me playing.

### If the game gets developed further and there’s more of a story to it, would you see yourself playing this on mobile or PC?

Obviously mobile because I don't think the genre of the game would compete with popular PC games.

** BTW ** We cannot see the enemies.

**Comment by LiliaIsABell** [comment]
**1. How does the speed feel to you? (the movement of the avatar, and the speed of the “endless running”)**
I thought the speed was nice. There were a couple of times I hoped to move forward using the right arrow key to move faster, but I do think the current is good. It could be fun if it got faster the further we go.

**2. Did you like the simple / minimalistic art style? Did you recognize that the background is supposed to be a forest?**
Yes I did! I thought the characters were very cute. When I first saw your background I thought they were velvet drapes like the ones in the theater. It wasn't until I read that it was a forest that I could then see the forest.

**3. If I decide to develop this idea further, each level would be a different colour background, which would be the various stages of a sun rising. In that case, the avatar is then running through the night and has to survive until the sun rises. What meaning do you attribute to this?**
If a character is trying to survive until sunrise, I immediately think that it is being chased or hunted. I think of every vampire movie I watched or the games "Until Dawn" and "Five Nights at Freddy's", and in all these examples the main character(s) are being pursued and are rescued at sunrise.

**4. When playing games like temple run, flappy bird, etc. (endless runners), how much do you care about the story? What do you notice the most about this format, that makes you keep playing?**
To be honest I don't always care about the story, because they usually don't have one. It is interest to create a setting, for example in "Subway Surfers" a vandal is being chased by a cop, but the game doesn't have a story telling element. We only play them because they are addicting and help time pass.

**5. If the game gets developed further and there’s more of a story to it, would you see yourself playing this on mobile or PC?**
Yes, definitely. I would be interesting to play an endless runner game that has a story that gets develop the longer you survive the game. There could be levels and trying to survive them to then see a cut scene but then it is no longer an endless runner.

**Comment by amandaclement** [comment]
**How does the speed feel to you? (the movement of the avatar, and the speed of the “endless running”)**
It feels too slow. I wish the speed was progressive to increase the difficulty as you go. Adding more ghosts or making them speed towards you could also help with this I think.

**Did you like the simple / minimalistic art style? Did you recognize that the background is supposed to be a forest?**
Yes, I think it works well for this type of game. In this context, I think that too much detail simply becomes distracting so I appreciate when things are kept simple. I thought the background was closed curtains and that I was on a stage. I'd recommend changing the colour hue and adding a bit more detail to the background like falling leaves to make it look more like a forest.

**If I decide to develop this idea further, each level would be a different colour background, which would be the various stages of a sun rising. In that case, the avatar is then running through the night and has to survive until the sun rises. What meaning do you attribute to this?**
Maybe the character is escaping a nightmare? I'm not really sure but if the intention is something similar to that, I think it would be nice if the character looked frightened every time a ghost appears. Adding sound effects would also help!

**When playing games like temple run, flappy bird, etc. (endless runners), how much do you care about the story? What do you notice the most about this format, that makes you keep playing?**
I'm not too concerned with the story but I do appreciate a clean design. I'm not big on these types of games but I guess they're good for killing time when sitting on the metro, waiting for an appointment, etc.

**If the game gets developed further and there’s more of a story to it, would you see yourself playing this on mobile or PC?**
Personally no but like I said, I'm not big on these types of games in general. I could definitely see it as more of a mobile game though!
